### ISSUE TITLE
Add some syntactic sugar around task contexts

### ISSUE THREAD

**Issue by aplowman** [LightForm-group/matflow#4]
If a task is to be executed twice, under two different contexts, and no other task parameters are different, we should be able to express the two contexts as a list on a single task, rather than by repeating the task. Instead of 

```yaml
  - name: dummy_task_2
    method: method_1    
    software: software_1
    base:
      parameter_3: 101
    context: multiaxial

  - name: dummy_task_2
    method: method_1    
    software: software_1
    base:
      parameter_3: 101
    context: uniaxial    
```
simplify to:

```yaml
  - name: dummy_task_2
    method: method_1    
    software: software_1
    base:
      parameter_3: 101
    contexts: [uniaxial, multiaxial]
```
