### ISSUE TITLE
Add default/optional parameters

### ISSUE THREAD

**Issue by aplowman** [LightForm-group/matflow#46]
Tasks should have a set of allowed and default parameters, so not all parameters need to be necessarily specified.

**Comment by aplowman** [comment]
An input can be made "optional" be specifying a default value in the schema:

```yaml
inputs:
  - name: parameter_1
    default: null
```
