### ISSUE TITLE
Failure for command-line parameter sequence of length 9 

### ISSUE THREAD

**Issue by aplowman** [LightForm-group/matflow#80]
E.g. task:
```yaml
  - name: generate_microstructure_seeds
    method: random
    software: damask
    base:
      grid_size: [16, 16, 16]
      num_grains: 3
    output_map_options:
      phase_label: Al      
    sequences:
      - name: num_grains
        vals: [1, 2, 3, 4, 5, 6, 7, 8, 9]
```
