### ISSUE TITLE
No groups defined in element_idx for tasks that have no local inputs specified

### ISSUE THREAD

**Issue by aplowman** [LightForm-group/matflow#82]
The following workflow fails:

```yaml
name: bug_local_input_groups
run_options:
  l: short
tasks:

    # input: parameter 1 (default)
    # output: parameter_2  
  - name: dummy_task_1
    method: method_1
    software: dummy_software
  
    # imput: parameter_2
    # output: parameter_5  
  - name: dummy_task_2d
    method: method_1
    software: dummy_software
  
    # inputs: parameter_5
    # outputs: parameter_6
  - name: dummy_task_3
    method: method_1
    software: dummy_software
```

with exception:

```
matflow.errors.UnsatisfiedGroupParameter: No group "default" defined in the workflow for input "parameter_5". Defined groups are: .
```

The problem is in the second task. It seems that since no local or default parameter values are used, the list element of `Workflow.element_idx` added for the second task during  `get_element_idx` is void of any groups (there should be a default group):

```
{'groups': {},
 'inputs': {'parameter_2': {'element_idx': [[0]],
                            'group': ['default'],
                            'local_input_idx': [None],
                            'task_idx': [0]}},
 'iteration_idx': [0],
 'num_elements': 1,
 'num_elements_per_iteration': 1,
 'num_iterations': 1}
```

Subsequently, the default group cannot be found when resolving the list element of `Workflow.element_idx` for the final task, which depends on the second task.

Tested on MatFlow v0.2.16.
